name: Windows Build (MinGW)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.2'
          host: 'windows'
          target: 'windows'
          arch: 'mingw'
          modules: 'qtconcurrent'
      - name: Configure CMake
        shell: bash
        run: |
          cmake -S . -B build `
            -G "MinGW Makefiles" `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_PREFIX_PATH=${{ env.QT_INSTALL_PATH }}
      - name: Build
        shell: bash
        run: cmake --build build --config Release
      - name: Package application
        shell: bash
        run: |
          cmake --install build --prefix ./install
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileXorProcessor-Windows-MinGW
          path: ./install/
