name: Windows · build (MSYS2 / MinGW-w64 + Qt6)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2 (install mingw toolchain, Qt6, cmake, ninja)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-qt6
            mingw-w64-x86_64-qt6-tools
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config

      - name: Debug info (show compilers / Qt)
        shell: msys2 {0}
        run: |
          echo "MSYSTEM=$MSYSTEM"
          which c++
          c++ --version
          which cmake
          cmake --version
          which qmake || true
          qmake --version || true
          echo "Qt pkgcmake dir: /mingw64/lib/cmake"
      
      - name: Configure & build (MSYS2 / MinGW shell)
        shell: msys2 {0}
        run: |
          set -e
          unset QT_ROOT_DIR || true
          unset QT_PLUGIN_PATH || true
          unset QML2_IMPORT_PATH || true

          CMAKE_PREFIX_PATH="/mingw64/lib/cmake"

          mkdir -p build
          cd build

          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}" \
            -S .. -B .

          JOBS=$(nproc || echo 2)
          cmake --build . --config Release --parallel ${JOBS}

      - name: Collect artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/*.exe
            build/**/*.exe
            build/*.dll
            build/**/*.dll
