name: Build Windows (MinGW + Qt)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-ntldd
            make

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.7.2
          host: windows
          target: desktop
          arch: win64_mingw
          cache: true
          modules: qttools
          set-env: true
          add-tools-to-path: true

      - name: Configure & Build
        shell: msys2 {0}
        run: |
          set -e
          QT_UNIX="$(cygpath -u "$QT_ROOT_DIR")"
          echo "Using QT (unix path): $QT_UNIX"

          mkdir -p build
          cd build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="$QT_UNIX/lib/cmake" \
            -S .. -B .
          JOBS=$(nproc || echo 2)
          cmake --build . --config Release -- -j${JOBS}

      - name: Deploy dependencies
        shell: msys2 {0}
        run: |
          set -e
          mkdir deploy
          cp build/FileXorProcessor.exe deploy/

          echo "=== Поиск зависимостей ==="
          ntldd -R deploy/FileXorProcessor.exe 2>/dev/null || true | grep "=> /mingw64" || true | awk '{print $3}' | sort -u > dll_list.txt

          echo "=== Копируем DLL ==="
          while IFS= read -r dll; do
            if [ -f "$dll" ]; then
              echo "Копируем: $dll"
              cp "$dll" deploy/
            fi
          done < dll_list.txt

          echo "=== Содержимое deploy/ ==="
          ls -l deploy

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileXorProcessor-Windows-x64
          path: deploy
